name: SyncToGitee
on: [push]
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          source-repo: "git@github.com:coderHDY/myblog.git" # github仓库地址
          destination-repo: "git@gitee.com:huangdeyu1996/myblog.git" # gitee仓库地址
          dst_key: ${{ secrets.MY_PRIVATE_KEY }} # 访问gitee 仓库需要的私钥
          dst_token: ${{ secrets.SYNC_GITHUB_KEY }} # gitee的 api access token
          static_list: "myblog"
          force_update: true