name: SyncToGitee
'on':
  - push
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/coderHDY
          dst: gitee/coderhdy
          dst_key: '${{ secrets.MY_PRIVATE_KEY }}'
          dst_token: '${{ secrets.GITEE_TOKEN }}'
          static_list: myblog
          force_update: true
